#ifndef MULTI_CORE_MATRIX_MULTIPLICATION_OMP_MM_H
#define MULTI_CORE_MATRIX_MULTIPLICATION_OMP_MM_H

void multiplyMatrixOMP(float *a, float *b, float *c, int size);

#endif //MULTI_CORE_MATRIX_MULTIPLICATION_OMP_MM_H
